lpzrobots/Makefile changed to compile and install modules onebyone

diff --git a/ga_tools/Makefile b/ga_tools/Makefile
--- a/ga_tools/Makefile
+++ b/ga_tools/Makefile
@@ -1,107 +1,190 @@
-# TODO: update this makefile! it will not work properly with -j 4
-#File:     Makefile for ga_tools package
+#File:     Makefile for ode_robot simulation framwwork
 #Author:   Georg Martius  <martius@informatik.uni-leipzig.de>
 #Date:     June 2005
 
-PACKAGE_NAME=ga_tools
-LPZROBOTS=..
-PACKAGE_PATH=.
-SELFORG=../selforg
-INCLUDEDIR=include/$(PACKAGE_NAME)
+
+SELFORGCFG=`if type selforg-config >/dev/null 2>&1; then echo "selforg-config"; elif [ -x ../selforg/selforg-config ]; then echo "../selforg/selforg-config"; else echo "Cannot find selforg-config" 1>&2; fi`
+
+
+PACKAGE=ga_tools
+INCLUDEDIR=include/$(PACKAGE)
+# this is the command to come from the include dir back to the base
 REVINCLUDEDIR=../..
-LIB=lib$(PACKAGE_NAME).a
-LIB_DBG=lib$(PACKAGE_NAME)_dbg.a
-LIB_OPT=lib$(PACKAGE_NAME)_opt.a
-LIB_PROF=lib$(PACKAGE_NAME)_prof.a
+
+# the CFGOPTS are set by the opt and dbg target
+CFGOPTS=
+LIB := $(shell ./$(PACKAGE)-config $(CFGOPTS) --srcprefix="." --libfile)
+SHAREDLIB=$(shell ./$(PACKAGE)-config $(CFGOPTS) --srcprefix="." --solibfile)
+TYPE=$(shell ./$(PACKAGE)-config --type)
+
+STRIP=no
+# this can is overwritten from commandline
+PREFIX=$(shell ./$(PACKAGE)-config $(CFGOPTS) --prefix)
+# for debian auto-package installation
+# this may not work....?
+ifneq ($(DESTDIR),) 
+PREFIX=$(DESTDIR)
+endif
+MAKEDEPEND=makedepend
+
+ifeq ($(TYPE),DEVEL)
+SELFORG=$(shell $(SELFORGCFG) $(CFGOPTS) --srcprefix)
+endif
 
 include Makefile.conf
 
+BUILD_DIR=build
+
 find_files = $(wildcard $(dir)/*.cpp)
 CPPFILES   := $(foreach dir,$(dirs),$(find_files))
-OFILES     := $(patsubst %.cpp,%.o, $(CPPFILES))
+OFILES     := $(patsubst %.cpp,${BUILD_DIR}/%.o, $(CPPFILES))
 find_h_files = $(wildcard $(dir)/*.h)
 HFILES   := $(foreach dir,$(dirs),$(find_h_files))
 
-# -pg for profiling
-CPPBASEFLAG = -Wall -Wno-deprecated -pipe -I. -pthread $(INC) 
-CPPFLAGS = $(CPPBASEFLAG) -g -O
+UTILS = install_prefix.conf
 
-## Debug (no optimization)
-CPPFLAGS_DBG = $(CPPBASEFLAG) -g
+# additional inc paths
+INC +=  -I. -Iinclude -Iinclude/$(PACKAGE) -I$(shell $(SELFORGCFG) $(CFGOPTS) --srcprefix)/include
 
-## Optimisation
-CPPFLAGS_OPT = $(CPPBASEFLAG) -O3 -DNDEBUG
-
-## Optimisation
-CPPFLAGS_PROF = $(CPPBASEFLAG)-O -DQPROF
+# use -pg for profiling
+CPPFLAGS = -Wall -pipe -fpic $(INC) $(shell $(SELFORGCFG) $(CFGOPTS) --cflags) \
+ $(shell ./$(PACKAGE)-config --srcprefix="." $(CFGOPTS) --intern --cflags)  
 
 # used for single file compilation
 CXX = g++
 
 # used for lib-packing 
-AR = ar -rs
+AR = ar -rcs
 
-.PHONY: lib opt clean distclean clean-all todo depend tags
+.PHONY: lib opt clean clean-all distclean todo depend tags search find findi install install_scripts install_lib uninstall uninstall_lib
 
-lib: $(UTILS) libselforg $(LIB)
+libs: lib opt dbg
 
-opt: $(UTILS) libselforg_opt $(LIB_OPT)
+lib: $(UTILS) 
+ifeq ($(TYPE),DEVEL)
+	cd $(SELFORG) && $(MAKE) lib
+endif
+	$(MAKE) library
 
-prof: $(UTILS) libselforg $(LIB_PROF)
+dbg: $(UTILS)
+ifeq ($(TYPE),DEVEL)
+	cd $(SELFORG) && $(MAKE) dbg
+endif
+	$(MAKE) BUILD_DIR=build_dbg CFGOPTS=--dbg library
 
-$(LIB): Makefile.depend $(SELFORG)/libselforg.a $(OFILES)
+opt: $(UTILS)
+ifeq ($(TYPE),DEVEL)
+	cd $(SELFORG) && $(MAKE) opt
+endif
+	$(MAKE) BUILD_DIR=build_opt CFGOPTS=--opt STRIP="yes" library
+
+shared:
+ifeq ($(TYPE),DEVEL)
+	cd $(SELFORG) && $(MAKE) shared
+endif
+	$(MAKE) $(SHAREDLIB)
+
+library: $(LIB)
+
+
+$(LIB): $(UTILS) Makefile.depend $(OFILES)	
 	$(AR) $(LIB) $(OFILES)
+	@if [ "$(STRIP)" = "yes" ]; then strip --strip-debug $(LIB); fi
 
-$(LIB_DBG): CPPFLAGS = $(CPPFLAGS_DBG)
-$(LIB_DBG): Makefile.depend $(SELFORG)/libselforg_dbg.a $(OFILES)
-	$(AR) $(LIB_DBG) $(OFILES)
+$(SHAREDLIB): Makefile.depend $(OFILES)
+	$(CXX) -shared -Wl,-soname,$(SHAREDLIB) -o $(SHAREDLIB) $(OFILES) 
 
-$(LIB_OPT): CPPFLAGS = $(CPPFLAGS_OPT)
-$(LIB_OPT): Makefile.depend $(SELFORG)/libselforg_opt.a $(OFILES)
-	$(AR) $(LIB_OPT) $(OFILES)
+${BUILD_DIR}/%.o: %.cpp
+	@mkdir -p $(dir $@)
+	$(CXX) -c $(CPPFLAGS) $(CFLAGS) -o "$@" "$<"
 
-$(LIB_PROF): CPPFLAGS = $(CPPFLAGS_PROF)
-$(LIB_PROF): Makefile.depend $(SELFORG)/libselforg.a $(OFILES)
-	$(AR) $(LIB_PROF) $(OFILES)
+${BUILD_DIR}/%.gch: %.cpp
+	@mkdir -p $(dir $@)
+	$(CXX) -c $(CPPFLAGS) $(CFLAGS) -o "$@" "$<"
 
-libselforg:	
-	+cd $(SELFORG) && make libselforg.a		
-
-libselforg_opt:	
-	+cd $(SELFORG) && make libselforg_opt.a		
-
+#%.o: %.cpp
+#	$(CXX) -c $(CPPFLAGS) $(CXXFLAGS) -o $(OBJDIR)/$(@F)  $< 
 
 Makefile.depend: 	
 	for file in $(HFILES); do \
 		ln -sf $(REVINCLUDEDIR)/$$file $(INCLUDEDIR)/; \
 	done
-	makedepend $(INC) $(CPPFILES) -f- > Makefile.depend 2>/dev/null
+	$(MAKEDEPEND) -- $(CPPFLAGS) -- $(CPPFILES) -p'$$(BUILD_DIR)/' -f- > Makefile.depend 2>/dev/null
 
 depend: 
 	rm Makefile.depend
 	make Makefile.depend
 
+
 tags:
 	etags ${CPPFILES} ${HFILES}
 	etags -a -o ../TAGS ${CPPFILES} ${HFILES} 
-
-#	etags `find -type f -regex ".*\.[hc]p?p?"` 
 
 ##!'search'           		ask for a search string and scans all tex files
 search:
 	echo -n "search rexp: "; read F && grep -in "$$F" ${CPPFILES} ${HFILES}
 
 
+##!'find'           		scans all tex files for the pattern stored in the file "tofind"
+find:
+	@[ -e "tofind" ] &&  grep -f tofind -n  ${CPPFILES} ${HFILES}
+
+
+##!'findi'           		case insensitive version of target `find'
+findi:
+	@[ -e "tofind" ] &&  grep -f tofind -in  ${CPPFILES} ${HFILES}
+
+
 distclean: clean-all
 clean-all: clean
-	rm -f $(LIB) $(LIB_DBG) $(LIB_OPT) $(LIB_PROF)
 
 clean:
 	rm -f Makefile.depend
+	rm -rf build build_dbg build_opt
+	rm -f $(SHAREDLIB)	
+	rm -f $(shell ./$(PACKAGE)-config --srcprefix="." --libfile)
+	rm -f $(shell ./$(PACKAGE)-config --opt --srcprefix="." --libfile)
+	rm -f $(shell ./$(PACKAGE)-config --dbg --srcprefix="." --libfile)
 	find $(INCLUDEDIR) -type l -exec rm \{\} \;
-	for dir in $(dirs); do \
-		rm -f $$dir/*.o; \
-	done
+
+
+install_scripts:
+	@echo "*************** Install binaries and scripts to $(PREFIX)/bin **********"
+	install -d $(PREFIX)/bin
+	install -m 755 $(PACKAGE)-config $(PREFIX)/bin/
+
+install_lib:
+	install -m 644 $(LIB) $(PREFIX)/lib/
+
+install: Makefile.depend install_scripts
+ifneq ($(TYPE),DEVEL)
+	@echo "*************** Install libs and includes $(PREFIX)*********************"
+	install -d  $(PREFIX)/lib $(PREFIX)/include/$(PACKAGE) 
+	$(MAKE) lib install_lib
+	$(MAKE) CFGOPTS=--dbg dbg install_lib
+	$(MAKE) CFGOPTS=--opt opt install_lib
+	install -m 644 include/$(PACKAGE)/*.h $(PREFIX)/include/$(PACKAGE)
+endif
+	install -d $(PREFIX)/share/lpzrobots $(PREFIX)/share/lpzrobots/$(PACKAGE)
+ifneq ($(TYPE),DEVEL)
+	@echo "*************** Install example simulations ******************"
+	cp -RL simulations $(PREFIX)/share/lpzrobots/$(PACKAGE)/
+	chmod -R ugo+r $(PREFIX)/share/lpzrobots/$(PACKAGE)
+endif
+
+uninstall_lib:
+	-rm -f $(PREFIX)/lib/$(LIB)
+
+uninstall:
+ifneq ($(TYPE),DEVEL)
+	$(MAKE) uninstall_lib
+	$(MAKE) CFGOPTS=--dbg uninstall_lib
+	$(MAKE) CFGOPTS=--opt uninstall_lib
+	-rm -rf $(PREFIX)/include/$(PACKAGE)
+endif
+	-rm -rf $(PREFIX)/share/lpzrobots/$(PACKAGE)/
+	-rm -f $(PREFIX)/bin/$(PACKAGE)-config
+
 
 install_prefix.conf:
 	@echo "create install_prefix.conf"
@@ -109,12 +192,8 @@ install_prefix.conf:
 	@echo '// e.g. #define PREFIX "/usr/local"'  >> install_prefix.conf
 
 todo:
-	grep -ni "Todo" $(CPPFILES) $(HFILES)
-	grep -ni "Fixme" $(CPPFILES) $(HFILES)
-
-FIND=`cat tofind`
-find:
-	@[ -n "$(FIND)" ] &&  grep -ni "$(FIND)"  $(CPPFILES) $(HFILES)
+	@grep -ni "Todo" $(CPPFILES) $(HFILES)
+	@grep -ni "Fixme" $(CPPFILES) $(HFILES)
 
 
 -include Makefile.depend
