further tuning of distribution stuff

diff --git a/dist_utils/create_deb_packages b/dist_utils/create_deb_packages
--- a/dist_utils/create_deb_packages
+++ b/dist_utils/create_deb_packages
@@ -2,24 +2,27 @@
 
 set -e # exit if command fails
 if [ $# -le 3 ]; then
-   echo "Usage $0 packdir packname version folder"
+   echo "Usage $0 packdir packname version folder [debfull]"
+   echo "    debfull means that the debian package is make completetly"
+   echo "    with source and binary but no ubuntu packages are build"
    exit 1
 fi 
 Packdir=$1
 PackName=$2
 Version=$3
 Folder=$4
+DebFull=$5
 
 pushd `pwd`
 
-mkdir -p "$Packdir"
-
-# tar the packages
-SOURCETGZ="${Folder}-${Version}.tgz"
-tar -czf "$SOURCETGZ" "${Folder}"
-# names them as package_version.orig.tar.gz
 ORIGTGZ="${PackName}_${Version}.orig.tar.gz"
-cp "$SOURCETGZ" "$Packdir/${ORIGTGZ}"
+if [ -e "$Packdir/${ORIGTGZ}" ]; then
+    echo "found $ORIGTGZ";
+else
+    echo "$ORIGTGZ not found in $Packdir!";
+    exit 1;
+fi
+    
 # untar them 
 cd "$Packdir"
 tar -xzf ${ORIGTGZ}
@@ -27,32 +30,39 @@ pushd `pwd`
 
 cd ${Folder}
 # first make debian unstable package
-debuild -S 
+if [ -n "$DebFull" ]; then # full package
+    echo "########## BUILD FULL DEBIAN PACKAGE ########### "
+    debuild
+else
+    debuild -S 
+fi
+
 # copy debian packages
 popd
 pushd `pwd`
 mkdir -p debian-unstable
 mv *.diff.gz *.build *.changes *.dsc debian-unstable
-# mv *.deb debian-unstable
 cp ${ORIGTGZ} debian-unstable
-# make ubuntu packages for launchpad
-mkdir -p ubuntu
-cd ${Folder}
-FIRST=""
-#for Dist in jaunty karmic lucid maverick; do
-for Dist in jaunty karmic; do
-    # change changelog for all ubuntu distributions  
-    dch --increment -D $Dist "$Dist version"
-    # make only source package
-    if [ -z "$FIRST" ]; then
-        debuild -S -sa
-    else
-        debuild -S
-    fi
-    FIRST="no"
-done
-popd
-cp ${ORIGTGZ} ubuntu
-mv *.diff.gz *.build *.changes *.dsc ubuntu
-
+if [ -n "$DebFull" ]; then 
+  mv *.deb debian-unstable
+else # make the ubuntu packages as well (only source)
+    # make ubuntu packages for launchpad
+    mkdir -p ubuntu
+    cd ${Folder}
+    FIRST=""
+    for Dist in jaunty karmic lucid maverick; do
+        # change changelog for all ubuntu distributions  
+        dch --increment -D $Dist "$Dist version"
+        # make only source package
+        if [ -z "$FIRST" ]; then
+            debuild -S -sa
+        else
+            debuild -S
+        fi
+        FIRST="no"
+    done
+    popd
+    cp ${ORIGTGZ} ubuntu
+    mv *.diff.gz *.build *.changes *.dsc ubuntu
+fi
 popd # return to place where we started
